// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using EF.Entities;
using FluentNHibernate.Mapping;

namespace NH.Mappings
{
	public class MediaMap: ClassMap<Media>
	{
		public MediaMap()
		{
			
			Id(t => t.Id, "Id");        
			  Table("Media");
			  Schema("dbo");
				Map(t => t.Value).Column("Value").Not.LazyLoad();	
				Map(t => t.MediaTypeId).Column("MediaTypeId").Not.LazyLoad();	
		}
	}
}
