// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using EF.Entities;
using FluentNHibernate.Mapping;

namespace NH.Mappings
{
	public class PersonMediaMap: ClassMap<PersonMedia>
	{
		public PersonMediaMap()
		{
			
			Id(t => t.Id, "Id");        
			  Table("PersonMedia");
			  Schema("dbo");
				Map(t => t.MediaId).Column("MediaId").Not.LazyLoad();	
				Map(t => t.PersonId).Column("PersonId").Not.LazyLoad();	
		}
	}
}
