// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using EF.Entities;
using FluentNHibernate.Mapping;

namespace NH.Mappings
{
	public class Persons_NonResidentPatientMap: ClassMap<Persons_NonResidentPatient>
	{
		public Persons_NonResidentPatientMap()
		{
			
			Id(t => t.Id, "Id");        
			  Table("Persons_NonResidentPatient");
			  Schema("dbo");
				Map(t => t.Id).Column("Id").Not.LazyLoad();	
		}
	}
}
