// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using EF.Entities;
using FluentNHibernate.Mapping;

namespace NH.Mappings
{
	public class RespirationMap: ClassMap<Respiration>
	{
		public RespirationMap()
		{
			
			Id(t => t.Id, "Id");        
			  Table("Respiration");
			  Schema("Vitals");
				Map(t => t.Id).Column("Id").Not.LazyLoad();	
				Map(t => t.UnitId).Column("UnitId").Not.LazyLoad();	
				Map(t => t.Value).Column("Value").Not.LazyLoad();	
		}
	}
}
