// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using SystemMessages;
using CommonMessages;
using EventAggregator;
using EventMessages;
using Interfaces;
using EF.Entities;
using Entity.Expressions;
using JB.Collections.Reactive;
using ReactiveUI;
using ViewModelInterfaces;

namespace ViewModels
{
	public partial class StepsSummaryListViewModel : ReactiveObject, ISummaryViewModel<IStepsAutoView>
	{
		private static readonly StepsSummaryListViewModel _instance;
		 static StepsSummaryListViewModel()
		{
			_instance = new StepsSummaryListViewModel();
		}

		public static StepsSummaryListViewModel Instance
		{
			get { return _instance; }
		}
		MessageSource msgSource => new MessageSource(this.ToString());

		private StepsSummaryListViewModel()
		{
			
			EventMessageBus.Current.GetEvent<EntitySetLoaded<IStepsAutoView>>(msgSource).Subscribe(x => handleEntitySetUpdated(x.Entities));
			EventMessageBus.Current.GetEvent<LoadEntityViewDataServiceStarted<ISteps>>(msgSource)
			   .Subscribe(x => EventMessageBus.Current.Publish(new LoadEntityView<ISteps>(StepsExpressions.StepsAutoViewExpression,typeof(IStepsAutoView), typeof(StepsAutoView), msgSource), msgSource));
		}

		private void handleEntitySetUpdated(IList<IStepsAutoView> entities)
		{
			EntitySet = new ObservableList<IStepsAutoView>(entities);
		}

		private ObservableList<IStepsAutoView> _EntitySet = new ObservableList<IStepsAutoView>();
		public ObservableList<IStepsAutoView> EntitySet
		{
			get
			{
				return _EntitySet;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _EntitySet, value ?? new ObservableList<IStepsAutoView>());
			}
		}

		private IStepsAutoView _currentEntity;

		public IStepsAutoView CurrentEntity
		{
			get { return _currentEntity; }
			set
			{
				if (!Equals(_currentEntity, value))
				{
					this.RaiseAndSetIfChanged(ref _currentEntity, value); //value == null? CreateEntity():value
					if (_currentEntity != null) EventMessageBus.Current.Publish(new CurrentEntityChanged<ISteps>(_currentEntity.Id,msgSource), msgSource);
				}
			}
		}

	}

}
