//// <autogenerated>
////   This file was generated by T4 code generator AllServices.tt.
////   Any changes made to this file manually will be lost next time the file is regenerated.
//// </autogenerated>


//using System;
//using System.Collections.Generic;
//using System.Collections.Concurrent;
//using System.Data.Entity.Infrastructure;
//using System.Data.Entity.Core;
//using System.Data.SqlClient;
//using System.Diagnostics;
//using System.ServiceModel;
//using System.Threading.Tasks;
////using System.Transactions;
//using TrackableEntities;
//using TrackableEntities.Common;
//using System.Linq.Dynamic;
//using System.ComponentModel.Composition;
//using OversShortQS.Business.Entities;
//using Core.Common.Contracts;
//using Core.Common.Business.Services;
//using TrackableEntities.EF6;
//using System.Data.Entity;
//using System.Linq;

//namespace OversShortQS.Business.Services
//{
//   [Export (typeof(IOverShortDetailsEXService))]
//   [Export(typeof(IBusinessService))]
//   [PartCreationPolicy(CreationPolicy.NonShared)]
//   [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall,
//                    ConcurrencyMode = ConcurrencyMode.Multiple)]
   
//    public partial class OverShortDetailsEXService : IOverShortDetailsEXService, IDisposable
//    {
//        //private readonly OversShortQSContext dbContext;

//        public bool StartTracking { get; set; }

//        public OverShortDetailsEXService()
//        {
//            try
//            {
//                // dbContext = new OversShortQSContext(){StartTracking = StartTracking};
//                StartTracking = false;
//             }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//        public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetails(List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {
//            //using (var scope = new TransactionScope(TransactionScopeOption.Required,
//                                   //new TransactionOptions() {IsolationLevel = IsolationLevel.ReadUncommitted}))
//               // {
//                  using ( var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                  {
//				    var set = AddIncludes(includesLst, dbContext);
//                    IEnumerable<OverShortDetailsEX> entities = await set.AsNoTracking().ToListAsync()
//													       .ConfigureAwait(continueOnCapturedContext: false);
//                           //scope.Complete();
//                            if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                            return entities;
//                   }
//                //}
//             }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }


//        public async Task<OverShortDetailsEX> GetOverShortDetailsEXByKey(string OverShortDetailId, List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {
//			   if(string.IsNullOrEmpty(OverShortDetailId))return null; 
//              using ( var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//              {
//                var i = Convert.ToInt32(OverShortDetailId);
//				var set = AddIncludes(includesLst, dbContext);
//                OverShortDetailsEX entity = await set.AsNoTracking().SingleOrDefaultAsync(x => x.OverShortDetailId == i).ConfigureAwait(continueOnCapturedContext: false);
//                if(tracking && entity != null) entity.StartTracking();
//                return entity;
//              }
//             }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }


//		 public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByExpression(string exp, List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//					if (string.IsNullOrEmpty(exp) || exp == "None") return new List<OverShortDetailsEX>();
//					var set = AddIncludes(includesLst, dbContext);
//                    if (exp == "All")
//                    {
//						var entities = await set.AsNoTracking().ToListAsync()
//											.ConfigureAwait(continueOnCapturedContext: false);

//                        if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                        return entities; 
//                    }
//					else
//					{
//						var entities = await set.AsNoTracking().Where(exp)
//											.ToListAsync() 
//											.ConfigureAwait(continueOnCapturedContext: false);
//                        if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                        return entities; 
											
//					}
					
//                }
//            }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		 public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByExpressionLst(List<string> expLst, List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//					if (expLst.Count == 0 || expLst.FirstOrDefault() == "None") return new List<OverShortDetailsEX>();
//					var set = AddIncludes(includesLst, dbContext);
//                    if (expLst.FirstOrDefault() == "All")
//                    {
//						var entities = await set.AsNoTracking().ToListAsync()
//											.ConfigureAwait(continueOnCapturedContext: false); 
//                        if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                        return entities; 
//                    }
//					else
//					{
//						set = AddWheres(expLst, set);
//						var entities = await set.AsNoTracking().ToListAsync() 
//										.ConfigureAwait(continueOnCapturedContext: false);
//                        if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                        return entities; 
											
//					}
					
//                }
//            }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByExpressionNav(string exp,
//																							  Dictionary<string, string> navExp,
//																							  List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {

//                    if (string.IsNullOrEmpty(exp) || exp == "None") return new List<OverShortDetailsEX>();

//                    if (exp == "All" && navExp.Count == 0)
//                    {
//                        var aentities = await AddIncludes(includesLst, dbContext)
//												.ToListAsync()
//												.ConfigureAwait(continueOnCapturedContext: false);
//                        if(tracking) aentities.AsParallel().ForAll(x => x.StartTracking());
//                        return aentities; 
//                    }
//                    foreach (var itm in navExp)
//                    {
//                        switch (itm.Key)
//                        {
//                            case "OverShortDetailAllocations":
//                                return
//                                    await
//                                        GetWhere<OverShortDetailAllocation>(dbContext, exp, itm.Value, "OverShortDetail", "Select", includesLst)
//										.ConfigureAwait(continueOnCapturedContext: false);

//                            case "OversShortEX":
//                                return
//                                    await
//                                        GetWhere<OversShortEX>(dbContext, exp, itm.Value, "", "SelectMany", includesLst)
//										.ConfigureAwait(continueOnCapturedContext: false);

//                            case "InventoryItem":
//                                return
//                                    await
//                                        GetWhere<InventoryItem>(dbContext, exp, itm.Value, "", "SelectMany", includesLst)
//										.ConfigureAwait(continueOnCapturedContext: false);

//                            case "OverShortAllocationsEXes":
//                                return
//                                    await
//                                        GetWhere<OverShortAllocationsEX>(dbContext, exp, itm.Value, "", "Select", includesLst)
//										.ConfigureAwait(continueOnCapturedContext: false);

//                        }

//                    }
//					var set = AddIncludes(includesLst, dbContext);
//                    var entities = await set.AsNoTracking().Where(exp)
//									.ToListAsync()
//									.ConfigureAwait(continueOnCapturedContext: false);
//                    if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                        return entities; 

//                }
//            }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//        public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByBatch(string exp,
//            int totalrow, List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {

//                var res = new ConcurrentQueue<List<OverShortDetailsEX>>();



//                if (string.IsNullOrEmpty(exp) || exp == "None") return new List<OverShortDetailsEX>();


//                var batchSize = 500;
//                var batches = Convert.ToInt32(totalrow / batchSize);

//                if (totalrow % batchSize > 0) batches += 1;
//                var exceptions = new ConcurrentQueue<Exception>();
//                Parallel.For(0, batches,
//                   new ParallelOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount * 2 },
//                    bat =>
//                    //  for (int bat = 0; bat < batches; bat++)
//                    {
//                        try
//                        {
//                            using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                            {
//                                dbContext.Configuration.AutoDetectChangesEnabled = false;
//                                //dbContext.Configuration.LazyLoadingEnabled = true;
//                                var set = AddIncludes(includesLst, dbContext);
//                                IQueryable<OverShortDetailsEX> dset;
//                                if (exp == "All")
//                                {
//                                    dset = set.OrderBy(x => x.OverShortDetailId);
//                                }
//                                else
//                                {
//                                    dset = set.OrderBy(x => x.OverShortDetailId).Where(exp);
//                                }

//                                var lst = dset
//                                    .Skip(bat * batchSize)
//                                    .Take(batchSize)
//                                    .ToList();
//                                res.Enqueue(lst);
//                            }

//                        }
//                        catch (Exception ex)
//                        {
//                            exceptions.Enqueue(ex);
//                        }
//                    }
//                    );
//                if (exceptions.Count > 0) throw new AggregateException(exceptions);
    
//                var entities = res.SelectMany(x => x.ToList());
//                if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                return entities; 

//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                var fault = new ValidationFault
//                {
//                    Result = false,
//                    Message = updateEx.Message,
//                    Description = updateEx.StackTrace
//                };
//                throw new FaultException<ValidationFault>(fault);
//            }
//        }
//        public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByBatchExpressionLst(List<string> expLst,
//            int totalrow, List<string> includesLst = null, bool tracking = true)
//        {
//            try
//            {

//                var res = new ConcurrentQueue<List<OverShortDetailsEX>>();



//                if (expLst.Count == 0 || expLst.FirstOrDefault() == "None") return new List<OverShortDetailsEX>();


//                var batchSize = 500;
//                var batches = Convert.ToInt32(totalrow / batchSize);

//                if (totalrow % batchSize > 0) batches += 1;
//                var exceptions = new ConcurrentQueue<Exception>();
//                Parallel.For(0, batches,
//                   new ParallelOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount * 2 },
//                    bat =>
//                    //  for (int bat = 0; bat < batches; bat++)
//                    {
//                        try
//                        {
//                            using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                            {
//                                dbContext.Configuration.AutoDetectChangesEnabled = false;
//                                //dbContext.Configuration.LazyLoadingEnabled = true;
//                                var set = AddIncludes(includesLst, dbContext);
//                                IQueryable<OverShortDetailsEX> dset;
//                                if (expLst.FirstOrDefault() == "All")
//                                {
//                                    dset = set.OrderBy(x => x.OverShortDetailId);
//                                }
//                                else
//                                {
//                                    set = AddWheres(expLst, set);
//                                    dset = set.OrderBy(x => x.OverShortDetailId);
//                                }

//                                var lst = dset
//                                    .Skip(bat * batchSize)
//                                    .Take(batchSize)
//                                    .ToList();
//                                res.Enqueue(lst);
//                            }

//                        }
//                        catch (Exception ex)
//                        {
//                            exceptions.Enqueue(ex);
//                        }
//                    }
//                    );
//                if (exceptions.Count > 0) throw new AggregateException(exceptions);
//                var entities = res.SelectMany(x => x.ToList());
//                if(tracking) entities.AsParallel(new ParallelLinqOptions() {MaxDegreeOfParallelism = Environment.ProcessorCount}).ForAll(x => x.StartTracking());
//                return entities; 
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                var fault = new ValidationFault
//                {
//                    Result = false,
//                    Message = updateEx.Message,
//                    Description = updateEx.StackTrace
//                };
//                throw new FaultException<ValidationFault>(fault);
//            }
//        }


//        public async Task<OverShortDetailsEX> UpdateOverShortDetailsEX(OverShortDetailsEX entity)
//        { 
//            using ( var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//              {
//                try
//                {   
//                    if(entity.TrackingState == TrackingState.Unchanged) entity.TrackingState = TrackingState.Modified;                              
                    
//                    dbContext.ApplyChanges(entity);
//                    await dbContext.SaveChangesAsync().ConfigureAwait(continueOnCapturedContext: false);
//                    entity.AcceptChanges();
//                    return entity;      

//                   // var entitychanges = entity.ChangeTracker.GetChanges();
//                   // if (entitychanges != null && entitychanges.FirstOrDefault() != null)
//                   // {
//                   //     dbContext.ApplyChanges(entitychanges);
//                   //     await dbContext.SaveChangesAsync().ConfigureAwait(continueOnCapturedContext: false);
//                   //     entity.EntityId = entitychanges.FirstOrDefault().EntityId;
//                   //     entity.AcceptChanges();     
//                   // }
//                   // return entity;        
//                }
//                catch (DbUpdateConcurrencyException dce)
//                {
//                    // Get failed entry
//                    foreach (var itm in dce.Entries)
//                    {
//                        if(itm.State != EntityState.Added)
//                         {
//                            var dv = itm.GetDatabaseValues();
//                            if(dv != null) itm.OriginalValues.SetValues(dv);
//                        }
//                    }
//                }
//                catch (OptimisticConcurrencyException oce)
//                {
//                    var context = ((IObjectContextAdapter)dbContext).ObjectContext;

//                    foreach (var entry in oce.StateEntries)
//                    {
//                        context.Refresh(System.Data.Entity.Core.Objects.RefreshMode.StoreWins, entry.Entity);
//                    }
//                }   
//                catch (DbUpdateException e)
//                {
                    
//                   // Debugger.Break();
//                    SqlException s = e.InnerException.InnerException as SqlException;
//                    if (s != null && s.Number == 2627)
//                    {
                         
//                    }
//                    else
//                    {
//                        Debugger.Break();
//                        throw;
//                    }
//                }             
//                catch (Exception updateEx)
//                {
//                    if (
//                        updateEx.Message.Contains(
//                            "The changes to the database were committed successfully, " +
//                            "but an error occurred while updating the object context"))
//                        return entity;

//                    System.Diagnostics.Debugger.Break();
//                    //throw new FaultException(updateEx.Message);
//                        var fault = new ValidationFault
//                                    {
//                                        Result = false,
//                                        Message = updateEx.Message,
//                                        Description = updateEx.StackTrace
//                                    };
//                        throw new FaultException<ValidationFault>(fault);
//                }
//            }
//           return entity;
//        }

//        public async Task<OverShortDetailsEX> CreateOverShortDetailsEX(OverShortDetailsEX entity)
//        {
//            try
//            {
//                using ( var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//              {
//                dbContext.Set<OverShortDetailsEX>().Add(entity);
//                await dbContext.SaveChangesAsync().ConfigureAwait(continueOnCapturedContext: false);
//                entity.AcceptChanges();
//                return entity;
//              }
//            }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//        public async Task<bool> DeleteOverShortDetailsEX(string OverShortDetailId)
//        {
//            try
//            {
//              using ( var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//              {
//                var i = Convert.ToInt32(OverShortDetailId);
//                OverShortDetailsEX entity = await dbContext.OverShortDetails.OfType<OverShortDetailsEX>()
//													.SingleOrDefaultAsync(x => x.OverShortDetailId == i)
//													.ConfigureAwait(continueOnCapturedContext: false);
//                if (entity == null)
//                    return false;

//                    dbContext.Set<OverShortDetailsEX>().Attach(entity);
//                    dbContext.Set<OverShortDetailsEX>().Remove(entity);
//                    await dbContext.SaveChangesAsync().ConfigureAwait(continueOnCapturedContext: false);
//                    return true;
//              }
//            }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		// Virtural list Implementation

//         public async Task<int> CountByExpressionLst(List<string> expLst)
//        {
//            try
//            {
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//                    if (expLst.Count == 0 || expLst.FirstOrDefault() == "None") return 0;
//                    var set = (IQueryable<OverShortDetailsEX>)dbContext.Set<OverShortDetailsEX>(); 
//                    if (expLst.FirstOrDefault() == "All")
//                    {
//                        return await set.AsNoTracking().CountAsync()
//                                            .ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                    else
//                    {
//                        set = AddWheres(expLst, set);
//                        return await set.AsNoTracking().CountAsync()
//                                        .ConfigureAwait(continueOnCapturedContext: false);
//                    }
                    
//                }
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                var fault = new ValidationFault
//                {
//                    Result = false,
//                    Message = updateEx.Message,
//                    Description = updateEx.StackTrace
//                };
//                throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		public async Task<int> Count(string exp)
//        {
//            try
//            {
//                using (OversShortQSContext dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//                    if (string.IsNullOrEmpty(exp) || exp == "None") return 0;
//                    if (exp == "All")
//                    {
//                        return await dbContext.Set<OverShortDetailsEX>()
//                                    .AsNoTracking()
//									.CountAsync()
//									.ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                    else
//                    {
                        
//                        return await dbContext.Set<OverShortDetailsEX>()
//									.AsNoTracking()
//                                    .Where(exp)
//									.CountAsync()
//									.ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                }
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }
        
//        public async Task<IEnumerable<OverShortDetailsEX>> LoadRange(int startIndex, int count, string exp)
//        {
//            try
//            {
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//                    if (string.IsNullOrEmpty(exp) || exp == "None") return new List<OverShortDetailsEX>();
//                    if (exp == "All")
//                    {
//                        return await dbContext.Set<OverShortDetailsEX>()
//										.AsNoTracking()
//                                        .OrderBy(y => y.OverShortDetailId)
//										.Skip(startIndex)
//										.Take(count)
//										.ToListAsync()
//										.ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                    else
//                    {
                        
//                        return await dbContext.Set<OverShortDetailsEX>()
//										.AsNoTracking()
//                                        .Where(exp)
//										.OrderBy(y => y.OverShortDetailId)
//										.Skip(startIndex)
//										.Take(count)
//										.ToListAsync()
//										.ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                }
//            }
//            catch (Exception updateEx)
//            {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		public async Task<int> CountNav(string exp, Dictionary<string, string> navExp)
//        {
//            try
//            {
//                if (string.IsNullOrEmpty(exp) || exp == "None") return 0;
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//                    if (exp == "All" && navExp.Count == 0)
//                    {
//                        return await dbContext.Set<OverShortDetailsEX>()
//										.AsNoTracking()
//                                        .CountAsync()
//										.ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                    foreach (var itm in navExp)
//                    {
//                        switch (itm.Key)
//                        {
//                            case "OverShortDetailAllocations":
//                                return await CountWhere<OverShortDetailAllocation>(dbContext, exp, itm.Value, "OverShortDetail", "Select")
//											.ConfigureAwait(continueOnCapturedContext: false);
//                            case "OversShortEX":
//                                return await CountWhere<OversShortEX>(dbContext, exp, itm.Value, "", "SelectMany")
//											.ConfigureAwait(continueOnCapturedContext: false);
//                            case "InventoryItem":
//                                return await CountWhere<InventoryItem>(dbContext, exp, itm.Value, "", "SelectMany")
//											.ConfigureAwait(continueOnCapturedContext: false);
//                            case "OverShortAllocationsEXes":
//                                return await CountWhere<OverShortAllocationsEX>(dbContext, exp, itm.Value, "", "Select")
//											.ConfigureAwait(continueOnCapturedContext: false);
//						}
//                    }
//                    return await dbContext.Set<OverShortDetailsEX>().Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//											.AsNoTracking()
//                                            .CountAsync()
//											.ConfigureAwait(continueOnCapturedContext: false);
//                }
                
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                var fault = new ValidationFault
//                {
//                    Result = false,
//                    Message = updateEx.Message,
//                    Description = updateEx.StackTrace
//                };
//                throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		private static async Task<int> CountWhere<T>(OversShortQSContext dbContext, string exp, string navExp, string navProp, string rel) where T : class
//        {
//              switch (rel)
//		    {
//		        case "SelectMany":
//                    return await CountWhereSelectMany<T>(dbContext, exp, navExp, navProp)
//									.ConfigureAwait(continueOnCapturedContext: false);
		            
//                default:
//                    return await CountWhereSelect<T>(dbContext, exp, navExp, navProp)
//									.ConfigureAwait(continueOnCapturedContext: false);
//		    }
//        }

//		private static async Task<int> CountWhereSelectMany<T>(OversShortQSContext dbContext, string exp, string navExp, string navProp) where T : class
//        {
//			try
//			{
//            return await dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .SelectMany(navProp).OfType<OverShortDetailsEX>()
//                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//                .Distinct()
//                .OrderBy("OverShortDetailId")
//                .CountAsync()
//				.ConfigureAwait(continueOnCapturedContext: false);
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//		private static async Task<int> CountWhereSelect<T>(OversShortQSContext dbContext, string exp, string navExp, string navProp) where T : class
//        {
//			try
//			{
//            return await dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .Select(navProp).OfType<OverShortDetailsEX>()
//                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//                .Distinct()
//                .OrderBy("OverShortDetailId")
//                .CountAsync()
//				.ConfigureAwait(continueOnCapturedContext: false);
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//		  public async Task<IEnumerable<OverShortDetailsEX>> LoadRangeNav(int startIndex, int count, string exp,
//                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null)
//        {
//            try
//            {
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//                    if ((string.IsNullOrEmpty(exp) && navExp.Count == 0) || exp == "None") return new List<OverShortDetailsEX>();
//                    var set = AddIncludes(includeLst, dbContext);

//                    if (exp == "All" && navExp.Count == 0)
//                    {
                       
//                        return await set
//									.AsNoTracking()
//                                    .OrderBy(y => y.OverShortDetailId)
 
//                                    .Skip(startIndex)
//                                    .Take(count)
//									.ToListAsync()
//									.ConfigureAwait(continueOnCapturedContext: false);
//                    }
//                    foreach (var itm in navExp)
//                    {
//                        switch (itm.Key)
//                        {
//                            case "OverShortDetailAllocations":
//                                return
//                                    await
//                                        LoadRangeWhere<OverShortDetailAllocation>(startIndex, count, dbContext, exp, itm.Value, "OverShortDetail", "Select")
//													.ConfigureAwait(continueOnCapturedContext: false);

//                            case "OversShortEX":
//                                return
//                                    await
//                                        LoadRangeWhere<OversShortEX>(startIndex, count, dbContext, exp, itm.Value, "", "SelectMany")
//													.ConfigureAwait(continueOnCapturedContext: false);

//                            case "InventoryItem":
//                                return
//                                    await
//                                        LoadRangeWhere<InventoryItem>(startIndex, count, dbContext, exp, itm.Value, "", "SelectMany")
//													.ConfigureAwait(continueOnCapturedContext: false);

//                            case "OverShortAllocationsEXes":
//                                return
//                                    await
//                                        LoadRangeWhere<OverShortAllocationsEX>(startIndex, count, dbContext, exp, itm.Value, "", "Select")
//													.ConfigureAwait(continueOnCapturedContext: false);

                          
//							default:
//                                throw new ArgumentException("No Navigation property found for " + itm.Key);
//						}

//                    }
//                    return await set//dbContext.Set<OverShortDetailsEX>()
//								.AsNoTracking()
//                                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//								.OrderBy(y => y.OverShortDetailId)
 
//                                .Skip(startIndex)
//                                .Take(count)
//								.ToListAsync()
//								.ConfigureAwait(continueOnCapturedContext: false);


//                }
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		private static async Task<IEnumerable<OverShortDetailsEX>> LoadRangeWhere<T>(int startIndex, int count,
//            OversShortQSContext dbContext, string exp, string navExp, string navProp, string rel, IEnumerable<string> includeLst = null) where T : class
//        {
//             switch (rel)
//		    {
//		        case "SelectMany":
//                    return await LoadRangeSelectMany<T>(startIndex, count, dbContext, exp, navExp, navProp, includeLst)
//									.ConfigureAwait(continueOnCapturedContext: false);
		            
//                default:
//                    return await LoadRangeSelect<T>(startIndex, count, dbContext, exp, navExp, navProp, includeLst)
//									.ConfigureAwait(continueOnCapturedContext: false);
//		    }
//        }

//		private static async Task<IEnumerable<OverShortDetailsEX>> LoadRangeSelectMany<T>(int startIndex, int count,
//            OversShortQSContext dbContext, string exp, string navExp, string navProp, IEnumerable<string> includeLst = null) where T : class
//        {
//			try
//			{
//            var set = dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .SelectMany(navProp).OfType<OverShortDetailsEX>();
    
//            if (includeLst != null) set = includeLst.Aggregate(set, (current, itm) => current.Include(itm));            

//            return await set
//                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//                .Distinct()
//                .OrderBy(y => y.OverShortDetailId)
 
//                .Skip(startIndex)
//                .Take(count)
//                .ToListAsync()
//				.ConfigureAwait(continueOnCapturedContext: false);
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//		private static async Task<IEnumerable<OverShortDetailsEX>> LoadRangeSelect<T>(int startIndex, int count,
//            OversShortQSContext dbContext, string exp, string navExp, string navProp, IEnumerable<string> includeLst = null) where T : class
//        {
//			try
//			{
//              var set = dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .Select(navProp).OfType<OverShortDetailsEX>();

//               if (includeLst != null) set = includeLst.Aggregate(set, (current, itm) => current.Include(itm)); 
                
//               return await set
//                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//                .Distinct()
//                .OrderBy(y => y.OverShortDetailId)
 
//                .Skip(startIndex)
//                .Take(count)
//                .ToListAsync()
//				.ConfigureAwait(continueOnCapturedContext: false);
//							 }
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//        private static async Task<IEnumerable<OverShortDetailsEX>> GetWhere<T>(OversShortQSContext dbContext,
//            string exp, string navExp, string navProp, string rel, List<string> includesLst = null) where T : class
//        {
//			try
//			{
//			    switch (rel)
//				{
//					case "SelectMany":
//						return await GetWhereSelectMany<T>(dbContext, exp, navExp, navProp, includesLst)
//										.ConfigureAwait(continueOnCapturedContext: false);
						
//					default:
//						return await GetWhereSelect<T>(dbContext, exp, navExp, navProp, includesLst)
//										.ConfigureAwait(continueOnCapturedContext: false);
//				}
			
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//		private static async Task<IEnumerable<OverShortDetailsEX>> GetWhereSelectMany<T>(OversShortQSContext dbContext,
//            string exp, string navExp, string navProp, List<string> includesLst = null) where T : class
//        {
//			try
//			{

//			if (includesLst == null)
//			{
//				return await dbContext.Set<T>()
//							.AsNoTracking()
//                            .Where(navExp)
//							.SelectMany(navProp).OfType<OverShortDetailsEX>()
//							.Where(exp == "All" || exp == null?"OverShortDetailId != null":exp)
//							.Distinct()
//							.ToListAsync()
//							.ConfigureAwait(continueOnCapturedContext: false);
//			}

//			var set = (DbQuery<OverShortDetailsEX>)dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .SelectMany(navProp).OfType<OverShortDetailsEX>()
//                .Where(exp == "All" || exp == null?"OverShortDetailId != null":exp)
//                .Distinct();

//			set = includesLst.Aggregate(set, (current, itm) => current.Include(itm));

//            return await set.ToListAsync()
//							.ConfigureAwait(continueOnCapturedContext: false);
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//		private static async Task<IEnumerable<OverShortDetailsEX>> GetWhereSelect<T>(OversShortQSContext dbContext,
//            string exp, string navExp, string navProp, List<string> includesLst = null) where T : class
//        {
//			try
//			{

//			if (includesLst == null)
//			{
//				return await dbContext.Set<T>()
//							.AsNoTracking()
//                            .Where(navExp)
//							.Select(navProp).OfType<OverShortDetailsEX>()
//							.Where(exp == "All" || exp == null?"OverShortDetailId != null":exp)
//							.Distinct()
//							.ToListAsync()
//							.ConfigureAwait(continueOnCapturedContext: false);
//			}

//			var set = (DbQuery<OverShortDetailsEX>)dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .Select(navProp).OfType<OverShortDetailsEX>()
//                .Where(exp == "All" || exp == null?"OverShortDetailId != null":exp)
//                .Distinct();

//			set = includesLst.Aggregate(set, (current, itm) => current.Include(itm));

//            return await set.ToListAsync()
//							.ConfigureAwait(continueOnCapturedContext: false);
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//			        public async Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsEXByOversShortsId(string OversShortsId, List<string> includesLst = null)
//        {
//            try
//            {
//                using ( var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//              {
//                var i = Convert.ToInt32(OversShortsId);
//                var set = AddIncludes(includesLst, dbContext);
//                IEnumerable<OverShortDetailsEX> entities = await set//dbContext.OverShortDetails.OfType<OverShortDetailsEX>()
//                                                    // .Include(x => x.OverShortAllocationsEXes)									  
//                                      .AsNoTracking()
//                                        .Where(x => x.OversShortsId.ToString() == OversShortsId.ToString())
//										.ToListAsync()
//										.ConfigureAwait(continueOnCapturedContext: false);
//                return entities;
//              }
//             }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }
//        }
 
//		public decimal SumField(string whereExp, string field)
//         {
//             try
//             {
//                 using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                 {
//					decimal res = 0;
//                     if (string.IsNullOrEmpty(whereExp) || whereExp == "None") return 0;
//                     if (whereExp == "All")
//                     {
//                          res = Convert.ToDecimal(dbContext.OverShortDetails.OfType<OverShortDetailsEX>().AsNoTracking().Sum(field));
//                     }
//                     else
//                     {
//                         res = Convert.ToDecimal(dbContext.OverShortDetails.OfType<OverShortDetailsEX>().AsNoTracking().Where(whereExp).Sum(field));
//                     }
                     
//                     return res;
//                 }
//             }
//             catch (Exception updateEx)
//             {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//             }
//         }

//        public async Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field)
//        {
//            try
//            {
//                if (string.IsNullOrEmpty(exp) || exp == "None") return 0;
//                using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                {
//                    if (exp == "All" && navExp.Count == 0)
//                    {
//                        return Convert.ToDecimal(dbContext.Set<OverShortDetailsEX>()
//										.AsNoTracking()
//                                        .Sum(field)??0);
//                    }
//                    foreach (var itm in navExp)
//                    {
//                        switch (itm.Key)
//                        {
//                            case "OverShortDetailAllocations":
//                                return await SumWhere<OverShortDetailAllocation>(dbContext, exp, itm.Value, "OverShortDetail", field, "Select")
//											.ConfigureAwait(continueOnCapturedContext: false);
//                            case "OversShortEX":
//                                return await SumWhere<OversShortEX>(dbContext, exp, itm.Value, "", field, "SelectMany")
//											.ConfigureAwait(continueOnCapturedContext: false);
//                            case "InventoryItem":
//                                return await SumWhere<InventoryItem>(dbContext, exp, itm.Value, "", field, "SelectMany")
//											.ConfigureAwait(continueOnCapturedContext: false);
//                            case "OverShortAllocationsEXes":
//                                return await SumWhere<OverShortAllocationsEX>(dbContext, exp, itm.Value, "", field, "Select")
//											.ConfigureAwait(continueOnCapturedContext: false);
//						}
//                    }
//                    return Convert.ToDecimal(dbContext.Set<OverShortDetailsEX>().Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//											.AsNoTracking()
//                                            .Sum(field)??0);
//                }
                
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                var fault = new ValidationFault
//                {
//                    Result = false,
//                    Message = updateEx.Message,
//                    Description = updateEx.StackTrace
//                };
//                throw new FaultException<ValidationFault>(fault);
//            }
//        }

//		private static async Task<decimal> SumWhere<T>(OversShortQSContext dbContext, string exp, string navExp, string navProp, string field, string rel) where T : class
//        {
//              switch (rel)
//		    {
//		        case "SelectMany":
//                    return await SumWhereSelectMany<T>(dbContext, exp, navExp, navProp, field)
//									.ConfigureAwait(continueOnCapturedContext: false);
//		        default:
//                    return await SumWhereSelect<T>(dbContext, exp, navExp, navProp, field)
//									.ConfigureAwait(continueOnCapturedContext: false);
//		    }
//        }

//		private static async Task<decimal> SumWhereSelectMany<T>(OversShortQSContext dbContext, string exp, string navExp, string navProp, string field) where T : class
//        {
//			try
//			{
//            return Convert.ToDecimal(dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .SelectMany(navProp).OfType<OverShortDetailsEX>()
//                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//                .Distinct()
//                .OrderBy("OverShortDetailId")
//                .Sum(field));
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }

//		private static async Task<decimal> SumWhereSelect<T>(OversShortQSContext dbContext, string exp, string navExp, string navProp, string field) where T : class
//        {
//			try
//			{
//            return Convert.ToDecimal(dbContext.Set<T>()
//				.AsNoTracking()
//                .Where(navExp)
//                .Select(navProp).OfType<OverShortDetailsEX>()
//                .Where(exp == "All" || exp == null ? "OverShortDetailId != null" : exp)
//                .Distinct()
//                .OrderBy("OverShortDetailId")
//                .Sum(field));
//			}
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//        }



//		 public string MinField(string whereExp, string field)
//         {
//             try
//             {
//                 using (var dbContext = new OversShortQSContext(){StartTracking = StartTracking})
//                 {
//					string res = "";
//                     if (string.IsNullOrEmpty(whereExp) || whereExp == "None") return res;
//                     if (whereExp == "All")
//                     {
//                          res = Convert.ToString(dbContext.OverShortDetails.OfType<OverShortDetailsEX>().AsNoTracking().Min(field));
//                     }
//                     else
//                     {
//                         res = Convert.ToString(dbContext.OverShortDetails.OfType<OverShortDetailsEX>().AsNoTracking().Where(whereExp).Min(field));
//                     }
                     
//                     return res;
//                 }
//             }
//             catch (Exception updateEx)
//             {
//                    System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//             }
//         }

		 
//		private static IQueryable<OverShortDetailsEX> AddIncludes(IEnumerable<string> includesLst, OversShortQSContext dbContext)
//       {
//		 try
//			{
//			   if (includesLst == null) includesLst = new List<string>();
//			   var set =(DbQuery<OverShortDetailsEX>) dbContext.OverShortDetails.OfType<OverShortDetailsEX>(); 
//			   set = includesLst.Where(x => !string.IsNullOrEmpty(x))
//                                .Aggregate(set, (current, itm) => current.Include(itm));
//			   return set;
//			 }
//			catch (Exception)
//			{
//				Debugger.Break();
//				throw;
//			}
//       }
//	   private IQueryable<OverShortDetailsEX> AddWheres(List<string> expLst, IQueryable<OverShortDetailsEX> set)
//        {
//            try
//            {
//                return expLst.Where(x => !string.IsNullOrEmpty(x))
//                             .Aggregate(set, (current, itm) => current.Where(itm));
//            }
//            catch (Exception)
//            {
//                Debugger.Break();
//                throw;
//            }
          
//        }

//        public void Dispose()
//        {
//            try
//            {
//               // var dispose = dbContext as IDisposable;
//             ////   if (dispose != null)
//            //    {
//           //         dbContext.Dispose();
//           //     }
//            }
//            catch (Exception updateEx)
//            {
//                System.Diagnostics.Debugger.Break();
//                //throw new FaultException(updateEx.Message);
//                    var fault = new ValidationFault
//                                {
//                                    Result = false,
//                                    Message = updateEx.Message,
//                                    Description = updateEx.StackTrace
//                                };
//                    throw new FaultException<ValidationFault>(fault);
//            }

//        }

//    }
//}



