// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class PrimaryKeyOptionsExpressions
	{
		public static IQueryable<PrimaryKeyOptions> GetPrimaryKeyOptionsById(this IQueryable<PrimaryKeyOptions> query, int Id) => query.Where(x => x.Id == Id);


// Get Leaf Properties
    
		public static IQueryable<PrimaryKeyOptions> GetPrimaryKeyOptions(this IQueryable<PrimaryKeyOptions> query) => query;

			// Child Properties
			//Parent Properties
				//public static IQueryable<PrimaryKeyOptions> PrimaryKeyOptions(this IQueryable<DataProperties> dataproperties) => dataproperties.Select(x => x.PrimaryKeyOptions);
				public static IQueryable<DataProperties> DataProperties(this IQueryable<PrimaryKeyOptions> query) => query.Select(x => x.DataProperties);
	}
}
