// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class TriggersExpressions
	{
		public static IQueryable<Triggers> GetTriggersById(this IQueryable<Triggers> query, int Id) => query.Where(x => x.Id == Id);


// Get Leaf Properties
    
		public static IQueryable<Triggers> GetTriggers(this IQueryable<Triggers> query) => query;

			// Child Properties
				public static IQueryable<StateMachineTriggers> StateMachineTriggers(this IQueryable<Triggers> triggers) => triggers.SelectMany(x => x.StateMachineTriggers);
				public static IQueryable<StateMachineTriggers> StateMachineTriggers(this IQueryable<Triggers> triggers, int id) => triggers.Where(x => x.Id == id).SelectMany(x => x.StateMachineTriggers);
			//Parent Properties
	}
}
