// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace EF.Entities
{
	public partial class PersonAddressInfo: BaseEntity, IPersonAddressInfo
	{
		public string City { get; set; }
		public string Country { get; set; }
		public string Parish { get; set; }
		public string State { get; set; }
		public string Addresstype { get; set; }

	}
}
