// <autogenerated>
//   This file was generated by T4 code generator MRManger-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;
using EF.Entities;

namespace Entity.Expressions
{
	public static partial class AddressesExpressions
	{

		public static Expression<Func<Addresses, AddressesAutoView>> AddressesAutoViewExpression { get; } =
		
			x => new AddressesAutoView 
			{
				Id = x.Id,
 				Cities = x.AddressCities.Cities.Name,   
 				Countries = x.AddressCountries.Countries.Name,   
 				AddressLines = x.AddressLines.Select(z => z.Name).FirstOrDefault(),   
 				Parishes = x.AddressParishes.Parishes.Name,   
 				States = x.AddressStates.States.Name,   
 				ZipCodes = x.AddressZipCodes.ZipCodes.Name,   
 				Organisations = x.OrganisationAddress.Select(x0 => x0.Organisations).Select(z => z.Name).FirstOrDefault(),   
			};
	}
}
