// <autogenerated>
//   This file was generated by T4 code generator MRManger-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;
using EF.Entities;

namespace Entity.Expressions
{
	public static partial class PatientVisitExpressions
	{

		public static Expression<Func<PatientVisit, PatientVisitAutoView>> PatientVisitAutoViewExpression { get; } =
		
			x => new PatientVisitAutoView 
			{
				Id = x.Id,
 				Syntoms = x.PatientSyntoms.Select(x0 => x0.Syntoms).Select(z => z.Name).FirstOrDefault(),   
 				Sex = x.Persons_Patient.Sex.Name,   
			};
	}
}
