// <autogenerated>
//   This file was generated by T4 code generator MRManger-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq.Expressions;
using EF.Entities;

namespace Entity.Expressions
{
	public static partial class PersonNamesExpressions
	{

		public static Expression<Func<PersonNames, PersonNamesAutoView>> PersonNamesAutoViewExpression { get; } =
		
			x => new PersonNamesAutoView 
			{
				Id = x.Id,
 				PersonNames = x.PersonName,   
			};
	}
}
