// <autogenerated>
//   This file was generated by T4 code generator MRManger-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;
using EF.Entities;

namespace Entity.Expressions
{
	public static partial class PersonsExpressions
	{

		public static Expression<Func<Persons, PersonsAutoView>> PersonsAutoViewExpression { get; } =
		
			x => new PersonsAutoView 
			{
				Id = x.Id,
 				Media = x.PersonMedia.Select(x0 => x0.Media).Select(z => z.Value).FirstOrDefault(),   
 				PersonNames = x.PersonNames.Select(z => z.PersonName).FirstOrDefault(),   
 				PhoneTypes = x.PersonPhoneNumbers.Select(x0 => x0.PhoneTypes).Select(z => z.Name).FirstOrDefault(),   
 				Sex = x.Persons_Patient.Sex.Name,   
 				Height = x.VitalSigns.Select(x1 => x1.Height).Select(z => z.Value).FirstOrDefault(),   
 				Pulse = x.VitalSigns.Select(x3 => x3.Pulse).Select(z => z.Value).FirstOrDefault(),   
 				Respiration = x.VitalSigns.Select(x4 => x4.Respiration).Select(z => z.Value).FirstOrDefault(),   
 				Temperature = x.VitalSigns.Select(x5 => x5.Temperature).Select(z => z.Value).FirstOrDefault(),   
 				Weight = x.VitalSigns.Select(x6 => x6.Weight).Select(z => z.Value).FirstOrDefault(),   
			};
	}
}
