// <autogenerated>
//   This file was generated by T4 code generator MRManger-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq.Expressions;
using EF.Entities;

namespace Entity.Expressions
{
	public static partial class ResponseSuggestions_InterviewsExpressions
	{

		public static Expression<Func<ResponseSuggestions_Interviews, ResponseSuggestions_InterviewsAutoView>> ResponseSuggestions_InterviewsAutoViewExpression { get; } =
		
			x => new ResponseSuggestions_InterviewsAutoView 
			{
				Id = x.Id,
			};
	}
}
