// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace EF.Entities
{
	public partial class VitalSignsAutoView: BaseEntity, IVitalSignsAutoView
	{
		public string Units { get; set; }
		public string HeightUnits { get; set; }
		public double? Height { get; set; }
		public string PulseUnits { get; set; }
		public int? Pulse { get; set; }
		public string RespirationUnits { get; set; }
		public int? Respiration { get; set; }
		public string TemperatureUnits { get; set; }
		public double? Temperature { get; set; }
		public string WeightUnits { get; set; }
		public double? Weight { get; set; }
		public string PersonNames { get; set; }
		public string UserSignIn { get; set; }

	}
}
