// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using Core.Common.UI;
using EF.Entities;
using DataInterfaces;
using Interfaces;
using Utilities;

namespace ViewModels
{
	public partial class PrimaryKeyOptionsViewModel_AutoGen 
	{
		public int Id  { get { return GetValue(); } set { SetValue(value); }
	    }

		protected override IPrimaryKeyOptions CreateEntity()
		{
			return new PrimaryKeyOptions() 
					{
						Id = BaseViewModel.CurrentDataProperties.Id, 
						RowState = DataInterfaces.RowState.Added
					};
		}
		protected override sealed IPrimaryKeyOptions CreateNullEntity()
		{
			return new PrimaryKeyOptions(){ Id = EntityStates.NullEntity };
		}
	
	}
}
