// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class PrimaryKeyOptionsViewModel_AutoGen 
	{
	   private static readonly PrimaryKeyOptionsViewModel_AutoGen instance;
	   static PrimaryKeyOptionsViewModel_AutoGen()
		{
			instance = new PrimaryKeyOptionsViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static PrimaryKeyOptionsViewModel_AutoGen Instance => instance;
	
	}
}
