// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class DataTypesViewModel_AutoGen 
	{
	   private static readonly DataTypesViewModel_AutoGen instance;
	   static DataTypesViewModel_AutoGen()
		{
			instance = new DataTypesViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static DataTypesViewModel_AutoGen Instance => instance;
	
	}
}
