// <autogenerated>
//   This file was generated by T4 code generator MRManger-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using EF.Entities;

namespace Entity.Expressions
{
	public static partial class AddressesExpressions
	{
		public static IQueryable<Addresses> GetAddressesById(this IQueryable<Addresses> query, int Id) => query.Where(x => x.Id == Id);


// Get Leaf Properties
    
		public static IQueryable<Cities> GetCities(this IQueryable<Addresses> query) => query.AddressCities().Cities();
    
		public static IQueryable<AddressCities> GetAddressCities(this IQueryable<Addresses> query) => query.AddressCities();
    
		public static IQueryable<Countries> GetCountries(this IQueryable<Addresses> query) => query.AddressCountries().Countries();
    
		public static IQueryable<AddressCountries> GetAddressCountries(this IQueryable<Addresses> query) => query.AddressCountries();
    
		public static IQueryable<AddressLines> GetAddressLines(this IQueryable<Addresses> query) => query.AddressLines();
    
		public static IQueryable<Parishes> GetParishes(this IQueryable<Addresses> query) => query.AddressParishes().Parishes();
    
		public static IQueryable<AddressParishes> GetAddressParishes(this IQueryable<Addresses> query) => query.AddressParishes();
    
		public static IQueryable<States> GetStates(this IQueryable<Addresses> query) => query.AddressStates().States();
    
		public static IQueryable<AddressStates> GetAddressStates(this IQueryable<Addresses> query) => query.AddressStates();
    
		public static IQueryable<ZipCodes> GetZipCodes(this IQueryable<Addresses> query) => query.AddressZipCodes().ZipCodes();
    
		public static IQueryable<AddressZipCodes> GetAddressZipCodes(this IQueryable<Addresses> query) => query.AddressZipCodes();
    
		public static IQueryable<AddressTypes> GetAddressTypes(this IQueryable<Addresses> query) => query.ForeignAddresses().AddressTypes();
    
		public static IQueryable<PrimaryPersonAddress> GetPrimaryPersonAddress(this IQueryable<Addresses> query) => query.PersonAddresses().PrimaryPersonAddress();
    
		public static IQueryable<PersonAddresses> GetPersonAddresses(this IQueryable<Addresses> query) => query.PersonAddresses();
    
		public static IQueryable<PersonEmailAddress> GetPersonEmailAddress(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonEmailAddress();
    
		public static IQueryable<MediaTypes> GetMediaTypes(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonMedia().Media().MediaTypes();
    
		public static IQueryable<DefaultImages> GetDefaultImages(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonMedia().Media().DefaultImages();
    
		public static IQueryable<PatientDoctor> GetPatientDoctor(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientDoctor();
    
		public static IQueryable<Persons_Doctor> GetPersons_Doctor(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().Persons_Doctor();
    
		public static IQueryable<Exams> GetExams(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamDetails().Exams();
    
		public static IQueryable<Components> GetComponents(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamDetails().ExamDetailComponents().Components();
    
		public static IQueryable<ExamDetailComponents> GetExamDetailComponents(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamDetails().ExamDetailComponents();
    
		public static IQueryable<ExamDetails> GetExamDetails(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamDetails();
    
		public static IQueryable<ExamResults_AnioticFluid> GetExamResults_AnioticFluid(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamResults_AnioticFluid();
    
		public static IQueryable<AssignedDating> GetAssignedDating(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamResults_FetalDates().AssignedDating();
    
		public static IQueryable<ExamResults_FetalDates> GetExamResults_FetalDates(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamResults_FetalDates();
    
		public static IQueryable<ResultFieldNames> GetResultFieldNames(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamResults_SimpleValues().ResultFieldNames();
    
		public static IQueryable<ExamResults_SimpleValues> GetExamResults_SimpleValues(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamResults_SimpleValues();
    
		public static IQueryable<ExamResults_UmbilicalArtery> GetExamResults_UmbilicalArtery(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults().ExamResults_UmbilicalArtery();
    
		public static IQueryable<ExamResults> GetExamResults(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults().ExamResults();
    
		public static IQueryable<PatientResults> GetPatientResults(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResults();
    
		public static IQueryable<Units> GetUnits(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().BloodPressure().Units();
    
		public static IQueryable<BloodPressure> GetBloodPressure(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().BloodPressure();
    
		public static IQueryable<Height> GetHeight(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().Height();
    
		public static IQueryable<Pulse> GetPulse(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().Pulse();
    
		public static IQueryable<Respiration> GetRespiration(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().Respiration();
    
		public static IQueryable<Temperature> GetTemperature(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().Temperature();
    
		public static IQueryable<Weight> GetWeight(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().Weight();
    
		public static IQueryable<VitalSigns> GetVitalSigns(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns();
    
		public static IQueryable<PatientVisitVitalSigns> GetPatientVisitVitalSigns(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().VitalSigns().PatientVisitVitalSigns();
    
		public static IQueryable<PatientVisit> GetPatientVisit(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit();
    
		public static IQueryable<Syntoms> GetSyntoms(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientSyntoms().Syntoms();
    
		public static IQueryable<PatientSyntoms> GetPatientSyntoms(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientSyntoms();
    
		public static IQueryable<Interviews> GetInterviews(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions().Interviews();
    
		public static IQueryable<Response> GetResponse(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Response();
    
		public static IQueryable<CarePlan> GetCarePlan(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions().ResponseOptions().ResponseSuggestions().ResponseSuggestions_CarePlans().CarePlan();
    
		public static IQueryable<ResponseSuggestions_CarePlans> GetResponseSuggestions_CarePlans(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions().ResponseOptions().ResponseSuggestions().ResponseSuggestions_CarePlans();
    
		public static IQueryable<ResponseSuggestions_Interviews> GetResponseSuggestions_Interviews(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions().ResponseOptions().ResponseSuggestions().ResponseSuggestions_Interviews();
    
		public static IQueryable<ResponseSuggestions> GetResponseSuggestions(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions().ResponseOptions().ResponseSuggestions();
    
		public static IQueryable<ResponseOptions> GetResponseOptions(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions().ResponseOptions();
    
		public static IQueryable<Questions> GetQuestions(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses().Questions();
    
		public static IQueryable<PatientResponses> GetPatientResponses(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientVisit().PatientResponses();
    
		public static IQueryable<ResponseImages> GetResponseImages(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonMedia().Media().ResponseImages();
    
		public static IQueryable<Media> GetMedia(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonMedia().Media();
    
		public static IQueryable<PersonMedia> GetPersonMedia(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonMedia();
    
		public static IQueryable<PersonNames> GetPersonNames(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonNames();
    
		public static IQueryable<PhoneTypes> GetPhoneTypes(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().ForeignPhoneNumbers().PhoneTypes();
    
		public static IQueryable<PrimaryPersonPhoneNumber> GetPrimaryPersonPhoneNumber(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonPhoneNumbers().PrimaryPersonPhoneNumber();
    
		public static IQueryable<PersonPhoneNumbers> GetPersonPhoneNumbers(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().PersonPhoneNumbers();
    
		public static IQueryable<Persons_EmergencyContact> GetPersons_EmergencyContact(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().Persons_EmergencyContact();
    
		public static IQueryable<Persons_NextOfKin> GetPersons_NextOfKin(this IQueryable<Addresses> query) => query.PersonAddresses().Persons().Persons_NextOfKin();
    
		public static IQueryable<Persons> GetPersons(this IQueryable<Addresses> query) => query.PersonAddresses().Persons();
    
		public static IQueryable<Sex> GetSex(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().Sex();
    
		public static IQueryable<Allergies> GetAllergies(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientAllergies().Allergies();
    
		public static IQueryable<PatientAllergies> GetPatientAllergies(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientAllergies();
    
		public static IQueryable<PatientReligon> GetPatientReligon(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PatientReligon();
    
		public static IQueryable<PersonCountryOfResidence> GetPersonCountryOfResidence(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PersonCountryOfResidence();
    
		public static IQueryable<Occupations> GetOccupations(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PersonJob().Occupations();
    
		public static IQueryable<Organisations> GetOrganisations(this IQueryable<Addresses> query) => query.OrganisationAddress().Organisations();
    
		public static IQueryable<PersonJob> GetPersonJob(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PersonJob();
    
		public static IQueryable<PersonMaritalStatus> GetPersonMaritalStatus(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient().PersonMaritalStatus();
    
		public static IQueryable<Persons_Patient> GetPersons_Patient(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_Patient();
    
		public static IQueryable<BoatInfo> GetBoatInfo(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().BoatInfo();
    
		public static IQueryable<ForeignPhoneNumbers> GetForeignPhoneNumbers(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().ForeignPhoneNumbers();
    
		public static IQueryable<NonResidentCompanyInfo> GetNonResidentCompanyInfo(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().NonResidentCompanyInfo();
    
		public static IQueryable<Organisations_Hotels> GetOrganisations_Hotels(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().NonResidentHotelInfo().Organisations_Hotels();
    
		public static IQueryable<NonResidentHotelInfo> GetNonResidentHotelInfo(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().NonResidentHotelInfo();
    
		public static IQueryable<Persons_ArrivalDepartureInfo> GetPersons_ArrivalDepartureInfo(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().Persons_ArrivalDepartureInfo();
    
		public static IQueryable<StudentInfo> GetStudentInfo(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient().StudentInfo();
    
		public static IQueryable<Persons_NonResidentPatient> GetPersons_NonResidentPatient(this IQueryable<Addresses> query) => query.ForeignAddresses().Persons_NonResidentPatient();
    
		public static IQueryable<ForeignAddresses> GetForeignAddresses(this IQueryable<Addresses> query) => query.ForeignAddresses();
    
		public static IQueryable<OrganisationAddress> GetOrganisationAddress(this IQueryable<Addresses> query) => query.OrganisationAddress();
    
		public static IQueryable<Addresses> GetAddresses(this IQueryable<Addresses> query) => query;

			// Child Properties
				public static IQueryable<AddressCities> AddressCities(this IQueryable<Addresses> addresses) => addresses.Select(x => x.AddressCities);
				public static IQueryable<AddressCities> AddressCities(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).Select(x => x.AddressCities);
				public static IQueryable<AddressCountries> AddressCountries(this IQueryable<Addresses> addresses) => addresses.Select(x => x.AddressCountries);
				public static IQueryable<AddressCountries> AddressCountries(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).Select(x => x.AddressCountries);
				public static IQueryable<AddressLines> AddressLines(this IQueryable<Addresses> addresses) => addresses.SelectMany(x => x.AddressLines);
				public static IQueryable<AddressLines> AddressLines(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).SelectMany(x => x.AddressLines);
				public static IQueryable<AddressParishes> AddressParishes(this IQueryable<Addresses> addresses) => addresses.Select(x => x.AddressParishes);
				public static IQueryable<AddressParishes> AddressParishes(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).Select(x => x.AddressParishes);
				public static IQueryable<AddressStates> AddressStates(this IQueryable<Addresses> addresses) => addresses.Select(x => x.AddressStates);
				public static IQueryable<AddressStates> AddressStates(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).Select(x => x.AddressStates);
				public static IQueryable<AddressZipCodes> AddressZipCodes(this IQueryable<Addresses> addresses) => addresses.Select(x => x.AddressZipCodes);
				public static IQueryable<AddressZipCodes> AddressZipCodes(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).Select(x => x.AddressZipCodes);
				public static IQueryable<ForeignAddresses> ForeignAddresses(this IQueryable<Addresses> addresses) => addresses.SelectMany(x => x.ForeignAddresses);
				public static IQueryable<ForeignAddresses> ForeignAddresses(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).SelectMany(x => x.ForeignAddresses);
				public static IQueryable<OrganisationAddress> OrganisationAddress(this IQueryable<Addresses> addresses) => addresses.SelectMany(x => x.OrganisationAddress);
				public static IQueryable<OrganisationAddress> OrganisationAddress(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).SelectMany(x => x.OrganisationAddress);
				public static IQueryable<PersonAddresses> PersonAddresses(this IQueryable<Addresses> addresses) => addresses.SelectMany(x => x.PersonAddresses);
				public static IQueryable<PersonAddresses> PersonAddresses(this IQueryable<Addresses> addresses, int id) => addresses.Where(x => x.Id == id).SelectMany(x => x.PersonAddresses);
			//Parent Properties
	}
}
