// <autogenerated>
//   This file was generated by T4 code generator MRManger-Expressions.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class AllergiesExpressions
	{
		public static IQueryable<Allergies> GetAllergiesById(this IQueryable<Allergies> query, int Id) => query.Where(x => x.Id == Id);


// Get Leaf Properties
    
		public static IQueryable<Allergies> GetAllergies(this IQueryable<Allergies> query) => query;

			// Child Properties
				public static IQueryable<PatientAllergies> PatientAllergies(this IQueryable<Allergies> allergies) => allergies.SelectMany(x => x.PatientAllergies);
				public static IQueryable<PatientAllergies> PatientAllergies(this IQueryable<Allergies> allergies, int id) => allergies.Where(x => x.Id == id).SelectMany(x => x.PatientAllergies);
			//Parent Properties
	}
}
