// <autogenerated>
//   This file was generated by T4 code generator MRManger-Expressions.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class MarketingMediumExpressions
	{
		public static IQueryable<MarketingMedium> GetMarketingMediumById(this IQueryable<MarketingMedium> query, int Id) => query.Where(x => x.Id == Id);


// Get Leaf Properties
    
		public static IQueryable<MarketingMedium> GetMarketingMedium(this IQueryable<MarketingMedium> query) => query;

			// Child Properties
			//Parent Properties
	}
}
