// <autogenerated>
//   This file was generated by T4 code generator MRManger-Expressions.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class NonResidentCompanyInfoExpressions
	{
		public static IQueryable<NonResidentCompanyInfo> GetNonResidentCompanyInfoById(this IQueryable<NonResidentCompanyInfo> query, int Id) => query.Where(x => x.Id == Id);


// Get Leaf Properties
    
		public static IQueryable<NonResidentCompanyInfo> GetNonResidentCompanyInfo(this IQueryable<NonResidentCompanyInfo> query) => query;

			// Child Properties
			//Parent Properties
				//public static IQueryable<NonResidentCompanyInfo> NonResidentCompanyInfo(this IQueryable<Persons_NonResidentPatient> persons_nonresidentpatient) => persons_nonresidentpatient.Select(x => x.NonResidentCompanyInfo);
				public static IQueryable<Persons_NonResidentPatient> Persons_NonResidentPatient(this IQueryable<NonResidentCompanyInfo> query) => query.Select(x => x.Persons_NonResidentPatient);
	}
}
