// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using Core.Common.UI;
using EF.Entities;
using DataInterfaces;
using Interfaces;
using Utilities;

namespace ViewModels
{
	public partial class StateMachineStatesViewModel_AutoGen 
	{
		public int MachineId  { get { return GetValue(); } set { SetValue(value); }
	    }
		public int Id  { get { return GetValue(); } set { SetValue(value); }
	    }
		public int StateId  { get { return GetValue(); } set { SetValue(value); }
	    }

		protected override IStateMachineStates CreateEntity()
		{
			return new StateMachineStates() 
					{
						MachineId = BaseViewModel.CurrentStateMachines.Id, 
						StateId = BaseViewModel.CurrentStates.Id, 
						RowState = DataInterfaces.RowState.Added
					};
		}
		protected override sealed IStateMachineStates CreateNullEntity()
		{
			return new StateMachineStates(){ Id = EntityStates.NullEntity };
		}
	
	}
}
