// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class EntityViewPropertyFunctionParameterViewModel_AutoGen 
	{
	   private static readonly EntityViewPropertyFunctionParameterViewModel_AutoGen instance;
	   static EntityViewPropertyFunctionParameterViewModel_AutoGen()
		{
			instance = new EntityViewPropertyFunctionParameterViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static EntityViewPropertyFunctionParameterViewModel_AutoGen Instance => instance;
	
	}
}
