// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using SystemMessages;
using CommonMessages;
using EventAggregator;
using EventMessages;
using Interfaces;
using EF.Entities;
using Entity.Expressions;
using JB.Collections.Reactive;
using ReactiveUI;
using ViewModelInterfaces;

namespace ViewModels
{
	public partial class StateMachinesSummaryListViewModel : ReactiveObject, ISummaryViewModel<IStateMachinesAutoView>
	{
		private static readonly StateMachinesSummaryListViewModel _instance;
		 static StateMachinesSummaryListViewModel()
		{
			_instance = new StateMachinesSummaryListViewModel();
		}

		public static StateMachinesSummaryListViewModel Instance
		{
			get { return _instance; }
		}
		MessageSource msgSource => new MessageSource(this.ToString());

		private StateMachinesSummaryListViewModel()
		{
			
			EventMessageBus.Current.GetEvent<EntitySetLoaded<IStateMachinesAutoView>>(msgSource).Subscribe(x => handleEntitySetUpdated(x.Entities));
			EventMessageBus.Current.GetEvent<LoadEntityViewDataServiceStarted<IStateMachines>>(msgSource)
			   .Subscribe(x => EventMessageBus.Current.Publish(new LoadEntityView<IStateMachines>(StateMachinesExpressions.StateMachinesAutoViewExpression,typeof(IStateMachinesAutoView), typeof(StateMachinesAutoView), msgSource), msgSource));
		}

		private void handleEntitySetUpdated(IList<IStateMachinesAutoView> entities)
		{
			EntitySet = new ObservableList<IStateMachinesAutoView>(entities);
		}

		private ObservableList<IStateMachinesAutoView> _EntitySet = new ObservableList<IStateMachinesAutoView>();
		public ObservableList<IStateMachinesAutoView> EntitySet
		{
			get
			{
				return _EntitySet;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _EntitySet, value ?? new ObservableList<IStateMachinesAutoView>());
			}
		}

		private IStateMachinesAutoView _currentEntity;

		public IStateMachinesAutoView CurrentEntity
		{
			get { return _currentEntity; }
			set
			{
				if (!Equals(_currentEntity, value))
				{
					this.RaiseAndSetIfChanged(ref _currentEntity, value); //value == null? CreateEntity():value
					if (_currentEntity != null) EventMessageBus.Current.Publish(new CurrentEntityChanged<IStateMachines>(_currentEntity.Id,msgSource), msgSource);
				}
			}
		}

	}

}
