// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class EntitiesAutoViewModel_AutoGen 
	{
	   private static readonly EntitiesAutoViewModel_AutoGen instance;
	   static EntitiesAutoViewModel_AutoGen()
		{
			instance = new EntitiesAutoViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static EntitiesAutoViewModel_AutoGen Instance => instance;
	
	}
}
