// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class FunctionReturnTypeViewModel_AutoGen 
	{
	   private static readonly FunctionReturnTypeViewModel_AutoGen instance;
	   static FunctionReturnTypeViewModel_AutoGen()
		{
			instance = new FunctionReturnTypeViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static FunctionReturnTypeViewModel_AutoGen Instance => instance;
	
	}
}
