// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class FunctionsViewModel_AutoGen 
	{
	   private static readonly FunctionsViewModel_AutoGen instance;
	   static FunctionsViewModel_AutoGen()
		{
			instance = new FunctionsViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static FunctionsViewModel_AutoGen Instance => instance;
	
	}
}
