// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SystemInterfaces;
using Common.Dynamic;


namespace EF.Entities
{
	public class EFEntity<T>: Expando where T: IEntity
	{
		public EFEntity()
		{
			
		}
		private EFEntity(int id)
		{
			Id = Id;
		}
		public EFEntity(object obj)
		{
			base.Initialize(obj);
		}
		public int Id { get; }
	}
}
