// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using Core.Common.UI;
using EF.Entities;
using DataInterfaces;
using Interfaces;
using Utilities;

namespace ViewModels
{
	public partial class EntityPropertiesViewModel_AutoGen 
	{
		public int Id  { get { return GetValue(); } set { SetValue(value); }
	    }
		public int EntityId  { get { return GetValue(); } set { SetValue(value); }
	    }
		public string PropertyName  { get { return GetValue(); } set { SetValue(value); }
	    }

		protected override IEntityProperties CreateEntity()
		{
			return new EntityProperties() 
					{
						EntityId = BaseViewModel.CurrentEntities.Id, 
						RowState = DataInterfaces.RowState.Added
					};
		}
		protected override sealed IEntityProperties CreateNullEntity()
		{
			return new EntityProperties(){ Id = EntityStates.NullEntity };
		}
	
	}
}
