// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using Core.Common.UI;
using Interfaces;

namespace ViewModels
{
	public partial class EntityPropertiesViewModel_AutoGen 
	{
	   private static readonly EntityPropertiesViewModel_AutoGen instance;
	   static EntityPropertiesViewModel_AutoGen()
		{
			instance = new EntityPropertiesViewModel_AutoGen();
			instance.WireEvents();
		}

	   public static EntityPropertiesViewModel_AutoGen Instance => instance;
	
	}
}
