// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using OversShortQS.Client.DTO;
using OversShortQS.Client.Contracts;
using Core.Common.Client.Services;

using Core.Common.Contracts;
using System.ComponentModel.Composition;


namespace OversShortQS.Client.Services
{
    [Export (typeof(OverShortAllocationsEXClient))]
    [Export (typeof(IOverShortAllocationsEXService))]
    [Export(typeof(IClientService))]
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public partial class OverShortAllocationsEXClient :  ClientService<IOverShortAllocationsEXService>, IOverShortAllocationsEXService, IDisposable
    {
        
        public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXes(List<string> includesLst = null)
        {
            return await Channel.GetOverShortAllocationsEXes(includesLst).ConfigureAwait(false);
        }

        public async Task<DTO.OverShortAllocationsEX> GetOverShortAllocationsEXByKey(string id, List<string> includesLst = null)
        {
            return await Channel.GetOverShortAllocationsEXByKey(id, includesLst).ConfigureAwait(false);
        }

		public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXesByExpression(string exp, List<string> includesLst = null)
        {
            return await Channel.GetOverShortAllocationsEXesByExpression(exp, includesLst).ConfigureAwait(false);
        }

		public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXesByExpressionLst(List<string> expLst, List<string> includesLst = null)
        {
            return await Channel.GetOverShortAllocationsEXesByExpressionLst(expLst, includesLst).ConfigureAwait(false);
        }

		public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXesByExpressionNav(string exp,
															 Dictionary<string, string> navExp, List<string> includesLst = null)
		{
			return await Channel.GetOverShortAllocationsEXesByExpressionNav(exp, navExp, includesLst).ConfigureAwait(false);
		}

        public async Task<IEnumerable<OverShortAllocationsEX>> GetOverShortAllocationsEXesByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null)
        {
            return await Channel.GetOverShortAllocationsEXesByBatch(exp, totalrow, includesLst).ConfigureAwait(false);
        }

        public async Task<IEnumerable<OverShortAllocationsEX>> GetOverShortAllocationsEXesByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null)
        {
            return await Channel.GetOverShortAllocationsEXesByBatchExpressionLst(expLst, totalrow, includesLst).ConfigureAwait(false);
        }

        public async Task<DTO.OverShortAllocationsEX> UpdateOverShortAllocationsEX(DTO.OverShortAllocationsEX entity)
        {
           return await Channel.UpdateOverShortAllocationsEX(entity).ConfigureAwait(false);
        }

        public async Task<DTO.OverShortAllocationsEX> CreateOverShortAllocationsEX(DTO.OverShortAllocationsEX entity)
        {
           return await Channel.CreateOverShortAllocationsEX(entity).ConfigureAwait(false);
        }

        public async Task<bool> DeleteOverShortAllocationsEX(string id)
        {
            return await Channel.DeleteOverShortAllocationsEX(id).ConfigureAwait(false);
        }

       // Virtural List implementation

        public async Task<int> CountByExpressionLst(List<string> expLst)
        {
            return await Channel.CountByExpressionLst(expLst).ConfigureAwait(continueOnCapturedContext: false);
        }
        
	    public async Task<int> Count(string exp)
        {
            return await Channel.Count(exp).ConfigureAwait(continueOnCapturedContext: false);
        }

		public async Task<int> CountNav(string exp, Dictionary<string, string> navExp)
        {
           return await Channel.CountNav(exp, navExp).ConfigureAwait(false);
        }

        public async Task<IEnumerable<DTO.OverShortAllocationsEX>> LoadRange(int startIndex, int count, string exp)
        {
            return await Channel.LoadRange(startIndex,count,exp).ConfigureAwait(false);
        }

		public async Task<IEnumerable<DTO.OverShortAllocationsEX>>  LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null)
        {
            return await Channel.LoadRangeNav(startIndex,count,exp, navExp, includeLst).ConfigureAwait(false);
        }
		public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXByOverShortDetailId(string OverShortDetailId, List<string> includesLst = null)
        {
            return  await Channel.GetOverShortAllocationsEXByOverShortDetailId(OverShortDetailId, includesLst).ConfigureAwait(false);
        }
			 
  		public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXByOversShortsId(string OversShortsId, List<string> includesLst = null)
        {
            return  await Channel.GetOverShortAllocationsEXByOversShortsId(OversShortsId, includesLst).ConfigureAwait(false);
        }
			 
  		public async Task<IEnumerable<DTO.OverShortAllocationsEX>> GetOverShortAllocationsEXByItem_Id(string Item_Id, List<string> includesLst = null)
        {
            return  await Channel.GetOverShortAllocationsEXByItem_Id(Item_Id, includesLst).ConfigureAwait(false);
        }
			 
          public decimal SumField(string whereExp, string sumExp)
		{
			return Channel.SumField(whereExp,sumExp);
		}

        public async Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field)
        {
            return await Channel.SumNav(exp,navExp,field).ConfigureAwait(false);
        }

		public string MinField(string whereExp, string sumExp)
		{
			return Channel.MinField(whereExp,sumExp);
		}

		#region IDisposable implementation

            /// <summary>
            /// IDisposable.Dispose implementation, calls Dispose(true).
            /// </summary>
            void IDisposable.Dispose()
            {
                Dispose(true);
            }

            /// <summary>
            /// Dispose worker method. Handles graceful shutdown of the
            /// client even if it is an faulted state.
            /// </summary>
            /// <param name="disposing">Are we disposing (alternative
            /// is to be finalizing)</param>
            protected new void Dispose(bool disposing)
            {
                if (disposing)
                {
                    try
                    {
                        if (State != CommunicationState.Faulted)
                        {
                            Close();
                        }
                    }
                    finally
                    {
                        if (State != CommunicationState.Closed)
                        {
                            Abort();
                        }
                        GC.SuppressFinalize(this);
                    }
                }
            }



            #endregion
    }
}

