// <autogenerated>
//   This file was generated by T4 code generator MRManger-Expressions.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class Persons_PatientExpressions
	{

		public static Expression<Func<Persons_Patient, PatientInfo>> Persons_PatientToPatientInfoExpression { get; } =
		
			x => new PatientInfo()
			{
				Id = x.Id,
				Email = x.Persons.PersonEmailAddress.Select(z => z.Email).StringJoin(","),
				PhoneNumber = x.Persons.PersonPhoneNumbers.Select(z => z.PhoneNumber).StringJoin(","),
				Country = x.PersonCountryOfResidence.Select(x2 => x2.Countries).Select(z => z.Name).StringJoin(","),
				DateOfBirth = x.DateOfBirth,
				CountryId = x.CountryId,
				Sexed = x.Sex.Name,
			};
	}
}
