// <autogenerated>
//   This file was generated by T4 code generator MRManger-Expressions.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace Entity.Expressions
{
	public static partial class ResponseOptionsExpressions
	{

		public static Expression<Func<ResponseOptions, ResponseOptionInfo>> ResponseOptionsToResponseOptionInfoExpression { get; } =
		
			x => new ResponseOptionInfo()
			{
				Id = x.Id,
				Responses = x.Response.Select(z => z.Value).StringJoin(","),
				Description = x.Description,
				Type = x.Type,
			};
	}
}
