// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using Core.Common.Contracts;
using OversShortQS.Client.DTO;

namespace OversShortQS.Client.Contracts
{
    [ServiceContract (Namespace="http://www.insight-software.com/WaterNut")]
    public partial interface IOverShortDetailsEXService : IClientService
    {
        [OperationContract]
        Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetails(List<string> includesLst = null);

        [OperationContract]
        Task<OverShortDetailsEX> GetOverShortDetailsEXByKey(string id, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByExpression(string exp, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByExpressionLst(List<string> expLst, List<string> includesLst = null);

		[OperationContract]
		Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByExpressionNav(string exp,
														 Dictionary<string, string> navExp, List<string> includesLst = null);        
        [OperationContract]
        Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null);
        [OperationContract]
        Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null);

		[OperationContract]
        Task<OverShortDetailsEX> UpdateOverShortDetailsEX(DTO.OverShortDetailsEX entity);

        [OperationContract]
        Task<OverShortDetailsEX> CreateOverShortDetailsEX(DTO.OverShortDetailsEX entity);

        [OperationContract]
        Task<bool> DeleteOverShortDetailsEX(string id);

		// Virtural List Implementation

        [OperationContract]
        Task<int> CountByExpressionLst(List<string> expLst);
    
		[OperationContract]
        Task<int> Count(string exp);

		[OperationContract]
        Task<int> CountNav(string exp, Dictionary<string, string> navExp);

        [OperationContract]
        Task<IEnumerable<OverShortDetailsEX>> LoadRange(int startIndex, int count, string exp);

		[OperationContract]
		Task<IEnumerable<OverShortDetailsEX>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null);

		[OperationContract]
		decimal SumField(string whereExp, string field);
        
        [OperationContract]
        Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field);

		[OperationContract]
		string MinField(string whereExp, string field);

				[OperationContract]
		Task<IEnumerable<OverShortDetailsEX>> GetOverShortDetailsEXByOversShortsId(string OversShortsId, List<string> includesLst = null);
        
  		
    }
}

