// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using Core.Common.UI;
using EF.Entities;
using DataInterfaces;
using Interfaces;
using Utilities;

namespace ViewModels
{
	public partial class ProcessStepScreensViewModel_AutoGen 
	{
		public int ProcessStepId  { get { return GetValue(); } set { SetValue(value); }
	    }
		public int Id  { get { return GetValue(); } set { SetValue(value); }
	    }
		public int ScreenId  { get { return GetValue(); } set { SetValue(value); }
	    }

		protected override IProcessStepScreens CreateEntity()
		{
			return new ProcessStepScreens() 
					{
						ProcessStepId = BaseViewModel.CurrentProcessSteps.Id, 
						ScreenId = BaseViewModel.CurrentScreens.Id, 
						RowState = DataInterfaces.RowState.Added
					};
		}
		protected override sealed IProcessStepScreens CreateNullEntity()
		{
			return new ProcessStepScreens(){ Id = EntityStates.NullEntity };
		}
	
	}
}
