// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using EF.Entities;
using FluentNHibernate.Mapping;

namespace NH.Mappings
{
	public class ApplicationSettingMap: ClassMap<ApplicationSetting>
	{
		public ApplicationSettingMap()
		{
			
			Id(t => t.Id, "Id");        
			  Table("ApplicationSettings");
			  Schema("dbo");
				Map(t => t.ApplicationId).Column("ApplicationId").Not.LazyLoad();	
				Map(t => t.SettingNameId).Column("SettingNameId").Not.LazyLoad();	
				Map(t => t.Value).Column("Value").Not.LazyLoad();	
		}
	}
}
