//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityViewProperty : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityViewProperty()
        {
            this.EntityViewPropertyFunctions = new HashSet<EntityViewPropertyFunction>();
            this.EntityViewViewProperties = new HashSet<EntityViewProperty>();
        }
    
        public string Name { get; set; }
        public int EntityViewId { get; set; }
    
        public virtual EntityView EntityView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityViewPropertyFunction> EntityViewPropertyFunctions { get; set; }
        public virtual EntityProperty EntityProperty { get; set; }
        public virtual EntityViewProperty EntityViewViewProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityViewProperty> EntityViewViewProperties { get; set; }
    }
}
