// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class ExamResults_FetalDatesMap
	{
		public static void Map(EntityTypeBuilder<ExamResults_FetalDates> entityBuilder)
		{
			entityBuilder.ToTable("ExamResults_FetalDates", "Diagnostics");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.ExamResultsId).HasColumnName("ExamResultsId").IsRequired();
			entityBuilder.Property(t => t.StartDate).HasColumnName("StartDate").IsRequired();
			entityBuilder.Property(t => t.Method).HasColumnName("Method").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Details).HasColumnName("Details").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.EstimatedDays).HasColumnName("EstimatedDays").IsRequired();
			entityBuilder.Property(t => t.PatientResultsId).HasColumnName("PatientResultsId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasOne(p => p.AssignedDating).WithOne(p => p.ExamResults_FetalDates).HasForeignKey<AssignedDating>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.ExamResults).WithMany(p => p.ExamResults_FetalDates).HasForeignKey(c => c.ExamResultsId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
