// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class ExamResults_UmbilicalArteryMap
	{
		public static void Map(EntityTypeBuilder<ExamResults_UmbilicalArtery> entityBuilder)
		{
			entityBuilder.ToTable("ExamResults_UmbilicalArtery", "Diagnostics");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Id).HasColumnName("Id").IsRequired();
			entityBuilder.Property(t => t.SDRatio).HasColumnName("SDRatio").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.ExamResults).WithOne(p => p.ExamResults_UmbilicalArtery).HasForeignKey<ExamResults>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
