// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class ParishesMap
	{
		public static void Map(EntityTypeBuilder<Parishes> entityBuilder)
		{
			entityBuilder.ToTable("Parishes", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.AddressParishes).WithOne(p => p.Parishes).HasForeignKey(c => c.ParishId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.ParishCities).WithOne(p => p.Parishes).HasForeignKey<ParishCities>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
	
		}
	}
}
