// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class PersonCountryOfResidenceMap
	{
		public static void Map(EntityTypeBuilder<PersonCountryOfResidence> entityBuilder)
		{
			entityBuilder.ToTable("PersonCountryOfResidence", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.CountryId).HasColumnName("CountryId").IsRequired();
			entityBuilder.Property(t => t.PersonId).HasColumnName("PersonId").IsRequired();
			entityBuilder.Property(t => t.Date).HasColumnName("Date").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.Countries).WithMany(p => p.PersonCountryOfResidence).HasForeignKey(c => c.CountryId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.Persons_Patient).WithMany(p => p.PersonCountryOfResidence).HasForeignKey(c => c.PersonId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
