// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class PersonJobMap
	{
		public static void Map(EntityTypeBuilder<PersonJob> entityBuilder)
		{
			entityBuilder.ToTable("PersonJob", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.OccupationId).HasColumnName("OccupationId").IsRequired();
			entityBuilder.Property(t => t.PersonId).HasColumnName("PersonId").IsRequired();
			entityBuilder.Property(t => t.OrganisationId).HasColumnName("OrganisationId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.Occupations).WithMany(p => p.PersonJob).HasForeignKey(c => c.OccupationId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.Persons_Patient).WithMany(p => p.PersonJob).HasForeignKey(c => c.PersonId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.Organisations).WithMany(p => p.PersonJob).HasForeignKey(c => c.OrganisationId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
