// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class QuestionsMap
	{
		public static void Map(EntityTypeBuilder<Questions> entityBuilder)
		{
			entityBuilder.ToTable("Questions", "Interview");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.EntityAttributeId).HasColumnName("EntityAttributeId").IsRequired();
			entityBuilder.Property(t => t.InterviewId).HasColumnName("InterviewId").IsRequired();
			entityBuilder.Property(t => t.Description).HasColumnName("Description").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.QuestionNumber).HasColumnName("QuestionNumber").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.PatientResponses).WithOne(p => p.Questions).HasForeignKey(c => c.QuestionId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.ResponseOptions).WithOne(p => p.Questions).HasForeignKey(c => c.QuestionId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.EntityAttributes).WithMany(p => p.Questions).HasForeignKey(c => c.EntityAttributeId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.Interviews).WithMany(p => p.Questions).HasForeignKey(c => c.InterviewId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
