// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;

namespace Interfaces
{
	[InheritedExport]
	public partial interface ISettingsAutoView:DataInterfaces.IEntity  
	{
		string Applications { get;}
		string Layers { get;}
		string Projects { get;}
		string Settings { get;}
		string SettingsSettings { get;}



	}
}
