//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class Medicine : Item
    {
        [DataMember]
        	public string SuggestedDosage
    	{ 
    		get { return _SuggestedDosage; }
    		set
    		{
    			if (Equals(value, _SuggestedDosage)) return;
    			_SuggestedDosage = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _SuggestedDosage;
        [DataMember]
        	public Nullable<System.DateTime> ExpiryDate
    	{ 
    		get { return _ExpiryDate; }
    		set
    		{
    			if (Equals(value, _ExpiryDate)) return;
    			_ExpiryDate = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<System.DateTime> _ExpiryDate;
    }
}
