// <autogenerated>
//   This file was generated by T4 code generator AllBusinessEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
//using Newtonsoft.Json;
using TrackableEntities;
using Core.Common.Business.Entities;


namespace OversShortQS.Business.Entities
{
    //[JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace="http://www.insight-software.com/WaterNut")]
    public partial class OverShortDetailsEX : OverShortDetail , ITrackable
    {
        partial void AutoGenStartUp() //OverShortDetailsEX()
        {
            this.OverShortAllocationsEXes = new List<OverShortAllocationsEX>();
        }

        [DataMember]
        public Nullable<double> ReceivedValue 
        {
            get
            {
                return _receivedvalue;
            }
            set
            {
                _receivedvalue = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        Nullable<double> _receivedvalue;
        [DataMember]
        public Nullable<double> InvoiceValue 
        {
            get
            {
                return _invoicevalue;
            }
            set
            {
                _invoicevalue = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        Nullable<double> _invoicevalue;
        [DataMember]
        public OversShortEX OversShortEX { get; set; }
        [DataMember]
        public InventoryItem InventoryItem { get; set; }
        [DataMember]
        public List<OverShortAllocationsEX> OverShortAllocationsEXes { get; set; }

 //       [DataMember]
 //       public TrackingState TrackingState { get; set; }
 //       [DataMember]
 //       public ICollection<string> ModifiedProperties { get; set; }
//        [DataMember]//JsonProperty,
 //       private Guid EntityIdentifier { get; set; }
    }
}


