// <autogenerated>
//   This file was generated by T4 code generator MRManger-Interfaces.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.ComponentModel.Composition;

namespace Interfaces
{
	[InheritedExport]
	public partial interface IExamResults_AnioticFluid:DataInterfaces.IEntity  
	{
		double AFI { get;}
		double MVP { get;}
		double Q1 { get;}
		double Q2 { get;}
		double Q3 { get;}
		double Q4 { get;}



	}
}
