//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverShortsQS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverShortSuggestedDocument
    {
        public int OversShortsId { get; set; }
        public string CNumber { get; set; }
        public string ReferenceNumber { get; set; }
    
        public virtual OversShortEX OversShortEX { get; set; }
    }
}
