//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverShortsQS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverShortDetail
    {
        public OverShortDetail()
        {
            this.OverShortDetailAllocations = new HashSet<OverShortDetailAllocation>();
        }
    
        public int OverShortDetailId { get; set; }
        public int OversShortsId { get; set; }
        public Nullable<double> ReceivedQty { get; set; }
        public string ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> InvoiceQty { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<OverShortDetailAllocation> OverShortDetailAllocations { get; set; }
    }
}
