//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverShortsQS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverShortDetailsEX : OverShortDetail
    {
        public OverShortDetailsEX()
        {
            this.OverShortAllocationsEXes = new HashSet<OverShortAllocationsEX>();
        }
    
        public Nullable<double> ReceivedValue { get; set; }
        public Nullable<double> InvoiceValue { get; set; }
    
        public virtual OversShortEX OversShortEX { get; set; }
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual ICollection<OverShortAllocationsEX> OverShortAllocationsEXes { get; set; }
    }
}
