// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class FunctionParametersMap
	{
		public static void Map(EntityTypeBuilder<FunctionParameters> entityBuilder)
		{
			entityBuilder.ToTable("FunctionParameters", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.FunctionId).HasColumnName("FunctionId").IsRequired();
			entityBuilder.Property(t => t.ParameterId).HasColumnName("ParameterId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.EntityViewPropertyFunctionParameter).WithOne(p => p.FunctionParameters).HasForeignKey(c => c.FunctionParameterId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.Functions).WithMany(p => p.FunctionParameters).HasForeignKey(c => c.FunctionId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.Parameters).WithMany(p => p.FunctionParameters).HasForeignKey(c => c.ParameterId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
