// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class StateMachinesMap
	{
		public static void Map(EntityTypeBuilder<StateMachines> entityBuilder)
		{
			entityBuilder.ToTable("StateMachines", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.StateMachineStates).WithOne(p => p.StateMachines).HasForeignKey(c => c.MachineId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.StateMachineTriggers).WithOne(p => p.StateMachines).HasForeignKey(c => c.MachineId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
	
		}
	}
}
